# Generated by Django 4.1.6 on 2023-03-22 11:56

import apps.person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.person.models.Person.get_file_path),
        ),
    ]
