# Generated by Django 4.1.6 on 2023-03-23 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(18)]),
            preserve_default=False,
        ),
    ]
