# Generated by Django 4.1.6 on 2023-03-23 20:08

import apps.person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_age'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.person.models.Person.get_file_path, verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
