# Generated by Django 4.1.6 on 2023-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_managers_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='User latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=2, max_digits=9, verbose_name='User longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
