# Generated by Django 4.1.6 on 2023-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_latitude_person_longitude_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
